name: bss
channels:
  - apple
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _r-mutex=1.0.1
  - aiobotocore=2.13.3
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - anyio=4.8.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - boto3=1.34.154
  - botocore=1.34.154
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.7.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cctools_osx-arm64=986
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - clang=18.1.8
  - clang-18=18.1.8
  - clang_impl_osx-arm64=18.1.8
  - clang_osx-arm64=18.1.8
  - clangxx=18.1.8
  - clangxx_impl_osx-arm64=18.1.8
  - clangxx_osx-arm64=18.1.8
  - comm=0.2.2
  - compiler-rt=18.1.8
  - compiler-rt_osx-arm64=18.1.8
  - contourpy=1.3.1
  - curl=8.14.1
  - cycler=0.12.1
  - debugpy=1.8.12
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - gfortran_impl_osx-arm64=13.4.0
  - gfortran_osx-arm64=13.4.0
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isl=0.26
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jmespath=1.0.1
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld64_osx-arm64=711
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=19.1.7
  - libcxx-devel=18.1.8
  - libdeflate=1.24
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.25.1
  - libgfortran=5.0.0
  - libgfortran-devel_osx-arm64=13.4.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libgoogle-cloud=2.35.0
  - libgoogle-cloud-storage=2.35.0
  - libgrpc=1.67.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.21
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.1
  - libpng=1.6.50
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - llvm-tools=18.1.8
  - llvm-tools-18=18.1.8
  - lz4-c=1.10.0
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - multidict=6.1.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - openjpeg=2.5.3
  - openssl=3.5.1
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.2
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus-cpp=1.3.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - propcache=0.2.1
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - r-base=4.2.3
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.23.1
  - rpy2=3.5.11
  - s3fs=2024.12.0
  - s3transfer=0.10.1
  - s5cmd=2.3.0
  - send2trash=1.8.3
  - setuptools=75.1.0
  - sigtool=0.1.3
  - simplegeneric=0.8.1
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.2
  - stack_data=0.6.3
  - tapi=1100.0.11
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - tzlocal=5.3
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - argparse==1.4.0
      - numpy==2.2.6
      - tqdm==4.67.1
prefix: /opt/anaconda3/envs/bss
